name: Demo Integration

# Only run when code lands on the main branch
on:
  push:
    branches:
      - main

jobs:
 # Build and publish Acme CRM component
  demo-component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
      - name: Install dependencies
        run: yarn install
      - name: Build Demo Component
        run: yarn build
        working-directory: components/acme-crm
      - name: Publish Demo Component
        uses: prismatic-io/component-publisher@v1.1
        with:
          COMPONENT_PATH: components/component
          PRISMATIC_URL: https://app.prismatic.io
          PRISM_REFRESH_TOKEN: ScZ2dqGn8ryNR3rCAAx4XYIIOxQjZC4llsSTMjeqlNI-

  # Publish Acme-Hooli integration
  demo-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Integration Component
        uses: prismatic-io/integration-publisher@v1.1
        with:
          PATH_TO_YML: integrations/ServiceTitan.yml
          PRISMATIC_URL: https://app.prismatic.io
          PRISM_REFRESH_TOKEN: CScZ2dqGn8ryNR3rCAAx4XYIIOxQjZC4llsSTMjeqlNI-
          INTEGRATION_ID:SW50ZWdyYXRpb246NGRiNzMyMDEtYzVhMi00NThkLWFlYjAtYmVlODk3OWE1YjZj/
          MAKE_AVAILABLE_IN_MARKETPLACE: true
